# Conclusion

The number of international students studying in the United States has been a common topic of discussion today. International students are vital to the exchange of ideas, innovation, economic prosperity, and peace among nations. There is no doubt that Asia, as a large population, has been the number one country for the total population of international students in the United States. Among them, China, India and South Korea are the major source countries of international students in the United States. At the same time, the total number of international students from Africa, Europe, and Latin America regions has also been on the rise since the 21st century.
Since 2020, the number of international students in the U.S. from around the world has changed significantly due to the severe impact of the epidemic. Until 2020, when the global epidemic broke out, the number of international students in the U.S. decreased significantly in all regions, especially in Asia, which we speculate was caused by Asian anti-epidemic policies that restricted immigration control or international political frictions. 
In addition, when we looked at the top 10 countries in terms of decrease in international students in the U.S. during COVID-19, Denmark as the country with the largest change in the number of international students in the U.S. since the 2000/01 academic year. It also saw a precipitous drop in headcount change from 2019.
Of course, international students around the world continue to value U.S. higher education, and we collectively expect a significant increase in the number of international students after the outbreak.
