--- 
title: "Changes of international students in the U.S. around the epidemic"
author: "Jiayuan Zhou, Wenqi Yu"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction


With the development of the global economy and politics, the cultural exchanges between countries are getting closer and closer. However, since 2016, the development of global study abroad has been affected by living environment and immigration policies, showing an overall slowdown in growth rate. Among them, the United Kingdom and the United States, which are traditionally strong countries for studying abroad, have seen a significant decline in the number of international students. Especially in the severe epidemic environment, studying in the United States has indeed brought many challenges to all international students. But America's charisma still has a huge impact compared to other developing countries. This comes from the large number of American universities and colleges, and the leading educational resources and academic level.


According to the report of the UNESCO Institute of Statistics, in recent years, the international students studying in the world are divided according to the continent to which the students originate. Asia ranks first with 57% of the students, followed by Europe, Africa, North America, South America, and Oceania. Since the issue of studying abroad is a common topic of discussion in society, data analysts have been studying the changes in the number of countries studying in the United States in recent years. Therefore, we decided to use exploratory data analysis to study what are the trends of international students in the 20th and 21st centuries,  what the number of international students in U.S. change during pandemic, and more detailed, for specific countries or regions, will the change before the COVID-19 period.